import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter_test/flutter_test.dart';
import 'package:immich_editor/export/jpeg.dart';

/// Orientation tag from IFD0 of an EXIF payload.
int orientation(Uint8List exif) {
  final d = ByteData.sublistView(exif);
  final e = exif[6] == 0x49 ? Endian.little : Endian.big;
  final ifd0 = 6 + d.getUint32(10, e);
  for (var n = 0; n < d.getUint16(ifd0, e); n++) {
    final entry = ifd0 + 2 + n * 12;
    if (d.getUint16(entry, e) == 0x0112) return d.getUint16(entry + 8, e);
  }
  return -1;
}

/// Segments with an identifier, e.g. 'Exif' or 'http://ns.adobe.com/xap'.
List<Uint8List> segments(Uint8List jpeg, String id) => [
  for (final s in parseSegments(jpeg).$1)
    if (latin1.decode(s.data.take(id.length).toList()) == id) s.data,
];

/// (Size of the primary image, absolute offset of the gain map) from the MPF directory
/// (MM-TIFF, as in the fixture).
(int, int) mpf(Uint8List jpeg) {
  var i = 2;
  while (!(jpeg[i + 1] == 0xE2 &&
      latin1.decode(jpeg.sublist(i + 4, i + 8)) == 'MPF\x00')) {
    i += 2 + ((jpeg[i + 2] << 8) | jpeg[i + 3]);
  }
  final tiff = i + 8;
  final d = ByteData.sublistView(jpeg);
  final entries = tiff + d.getUint32(tiff + 8 + 2 + 2 * 12 + 8);
  return (d.getUint32(entries + 4), tiff + d.getUint32(entries + 16 + 8));
}

Future<ui.Image> decode(Uint8List jpeg) async =>
    (await (await ui.instantiateImageCodec(jpeg)).getNextFrame()).image;

void main() {
  // 4×2 pixels stored, EXIF orientation 6 (90° clockwise).
  final rotated = File('test/fixtures/orient6.jpg').readAsBytesSync();
  // Structured like Android's Ultra HDR output; generated by ultrahdr_small.py.
  final ultraHdr = File('test/fixtures/ultrahdr_small.jpg').readAsBytesSync();

  test('reads EXIF and sets orientation to 1', () {
    final exif = exifFrom(rotated)!;
    expect(latin1.decode(exif.sublist(0, 6)), 'Exif\x00\x00');
    expect(orientation(exif), 6);
    normalizeOrientation(exif);
    expect(orientation(exif), 1);
  });

  test('no EXIF: null', () {
    expect(
      exifFrom(Uint8List.fromList([0xFF, 0xD8, 0xFF, 0xDA, 0, 2])),
      isNull,
    );
  });

  testWidgets('without XMP: new packet, EXIF replaced, decodable', (t) async {
    final exif = exifFrom(rotated)!;
    normalizeOrientation(exif);
    final out = assemble(
      rotated,
      exif: exif,
      recipe: {'v': 1, 'brightness': 0.25},
      originalSha1: 'ab+/c=',
    );
    expect(segments(out, 'Exif'), [exif]);
    final xmp = segments(out, 'http://ns.adobe.com/xap');
    expect(xmp, hasLength(1));
    final text = utf8.decode(xmp.single);
    expect(text, contains('xmlns:ife="$recipeNamespace"'));
    expect(text, contains('ife:originalSha1="ab+/c="'));
    expect(
      text,
      contains('ife:recipe="{&quot;v&quot;:1,&quot;brightness&quot;:0.25}"'),
    );
    // Orientation now 1: the stored 4×2 pixels stay 4×2.
    final image = (await t.runAsync(() => decode(out)))!;
    expect([image.width, image.height], [4, 2]);
  });

  testWidgets('Ultra HDR: one EXIF, one XMP, MPF points to the gain map', (
    t,
  ) async {
    final (_, oldGainMap) = mpf(ultraHdr);
    final gainMap = ultraHdr.sublist(oldGainMap);
    final exif = exifFrom(rotated)!;
    normalizeOrientation(exif);

    final out = assemble(
      ultraHdr,
      exif: exif,
      recipe: {'v': 1},
      originalSha1: 'x',
    );

    expect(segments(out, 'Exif'), [exif]); // the encoder's is replaced
    final xmp = utf8.decode(segments(out, 'http://ns.adobe.com/xap').single);
    expect(xmp, contains('hdrgm:Version="1.0"'));
    expect(xmp, contains('Item:Semantic="GainMap"'));
    expect(xmp, contains('ife:recipe='));

    final (primary, newGainMap) = mpf(out);
    expect(newGainMap, primary); // gain map right after the primary image
    expect(out.sublist(newGainMap), gainMap); // unchanged, at the end
    expect(out.sublist(primary - 2, primary), [0xFF, 0xD9]); // EOI before it
    final image = (await t.runAsync(() => decode(out)))!;
    expect([image.width, image.height], [8, 4]);
  });

  test('recipeFrom reads recipe and checksum back', () {
    final copy = assemble(
      ultraHdr,
      recipe: {
        'v': 1,
        'contrast': 0.25,
        'geometry': {'angle': -2.5},
      },
      originalSha1: 'ab+/c=',
    );
    final r = recipeFrom(copy)!;
    expect(r.originalSha1, 'ab+/c=');
    expect(r.recipe, {
      'v': 1,
      'contrast': 0.25,
      'geometry': {'angle': -2.5},
    });
    expect(recipeFrom(rotated), isNull); // no recipe
  });

  test('recipeFrom also reads from the head of a file', () {
    final copy = assemble(ultraHdr, recipe: {'v': 1}, originalSha1: 's');
    final xmpEnd = copy.length ~/ 2; // cut somewhere after the XMP
    expect(
      recipeFrom(Uint8List.sublistView(copy, 0, xmpEnd))?.originalSha1,
      's',
    );
    expect(
      recipeFrom(Uint8List.sublistView(copy, 0, 30)),
      isNull,
    ); // in the middle of the EXIF
  });
}
